In [4]:
import numpy as np

In [11]:
5 // 2

2

In [19]:
import numbers

In [13]:
stride = 1

In [21]:
if isinstance(stride, numbers.Number):
    stride= (stride, stride)

In [15]:
stride= (stride, stride)

In [18]:
isinstance(stride,numbers)

NameError: name 'numbers' is not defined

In [2]:
x1=np.array([1,2,3])
x2=np.array([2,4])
np.concatenate([x1,x2],axis=0)

array([1, 2, 3, 2, 4])

In [7]:
x1=np.array([1,2,3,4])
x1=x1.reshape(2,2)
np.mean(x1,axis=0)

array([2., 3.])

In [8]:
x1

array([[1, 2],
       [3, 4]])

In [3]:
for i in xrange(2):
    print(i)

NameError: name 'xrange' is not defined